export const VERSION=1;
export const CATEGORIES={fruit:'Fruit',veg:'Vegetables',dairy:'Dairy',meat:'Meat & poultry',seafood:'Seafood',bakery:'Bakery',ready:'Ready meals'};
export const PRODUCTS={strawberries:{label:'Strawberries',cat:'fruit',life:96,ref:4,price:9},bananas:{label:'Bananas',cat:'fruit',life:168,ref:14,price:4},tomatoes:{label:'Tomatoes',cat:'veg',life:120,ref:8,price:4},greens:{label:'Leafy greens',cat:'veg',life:72,ref:4,price:6},milk:{label:'Milk',cat:'dairy',life:240,ref:4,price:2},yoghurt:{label:'Yoghurt',cat:'dairy',life:480,ref:4,price:6},cheese:{label:'Soft cheese',cat:'dairy',life:336,ref:4,price:18},chicken:{label:'Chicken',cat:'meat',life:120,ref:2,price:12},mince:{label:'Beef mince',cat:'meat',life:72,ref:2,price:14},fish:{label:'Fresh fish',cat:'seafood',life:48,ref:1,price:28},bread:{label:'Bread',cat:'bakery',life:96,ref:20,price:7},meals:{label:'Ready meals',cat:'ready',life:72,ref:4,price:15}};
export const CLIMATE={factor:2.1,factorSource:'Australian National Greenhouse Accounts Factors 2023: food waste to landfill, 2.1 t CO2-e per tonne',factorUrl:'https://www.dcceew.gov.au/sites/default/files/documents/national-greenhouse-account-factors-2023.pdf'};
export const HIERARCHY=[['prevent','Prevent','Sell or use first, price to clear'],['feed','Feed people','Donate while quality remains'],['check','Check','Staff inspection before any release'],['recover','Recover','Compost or anaerobic digestion, never landfill']];
export const SECTORS={retail:'Retail',hospitality:'Hospitality',production:'Food production'};
export const EPICS=[
 ['E01','Batch inventory','Add and filter batches, inspect remaining stock, place or release a manual hold.','Madhumitha + Vijayaraja'],
 ['E02','Expiry Twin','Timestamped temperature history, illustrative effective-age model, data-quality gates.','Abhishek + Shyam'],
 ['E03','Demand forecasts','Record sales or usage, seven-day baseline, manual forecasts, recipe and yield conversion.','Madhumitha + Shyam'],
 ['E04','Integrated stock plan','Freshness-prioritised allocation, eligible carryover, inbound receipts and replenishment.','Shyam + Vijayaraja'],
 ['E05','Intervention comparison','Compare ordinary rotation, use-first, markdown and eligible transfer scenarios.','Abhishek + Madhumitha'],
 ['E06','Review and decisions','Propose actions, require staff checks, invalidate stale approvals and keep an audit trail.','Madhumitha + Vijayaraja'],
 ['E07','Outcome ledger','Record actual sales, use, donation, transfer and discard with quantity limits.','Vijayaraja + Shyam'],
 ['E08','Evidence and handover','Separate estimates and recorded outcomes, CSV reports, JSON backup/restore and project docs.','Nithilan + Madhumitha'],
 ['E09','Climate lens and rescue ladder','Kg at risk of waste per scenario, cited landfill CO₂-e factor, food-recovery-hierarchy next actions, freshness chart, what-if storage and guided demo.','Team to confirm']
];
export const iso=t=>new Date(t).toISOString();
export const hours=(a,b)=>(new Date(a)-new Date(b))/36e5;
export const finite=(v,min=0,max=1e7)=>typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max;
export const uid=()=>globalThis.crypto?.randomUUID?.()||`id-${Date.now()}-${Math.random().toString(36).slice(2)}`;
export function seed(){const now=Date.parse('2026-10-04T06:00:00Z');const batches=[['ST-A','strawberries',24,4],['ST-B','strawberries',24,22],['TM-A','tomatoes',40,8],['GR-A','greens',16,4]].map(([id,product,quantity,temp])=>({id,product,quantity,received:iso(now-24*36e5),limit:iso(now+48*36e5),location:id==='ST-B'?'Loading bay':'Cold room',hold:false,sensors:[-24,-18,-12,-6,0].map((h,i)=>({at:iso(now+h*36e5),temperature:i===0||i===4?PRODUCTS[product].ref:temp}))}));
for(const [id,product,quantity,temp,location] of [['BN-A','bananas',30,14,'Ambient store'],['MK-A','milk',60,4,'Dairy chiller'],['MK-B','milk',40,9,'Delivery dock'],['YG-A','yoghurt',25,4,'Dairy chiller'],['CS-A','cheese',8,4,'Deli chiller'],['CK-A','chicken',30,2,'Meat chiller'],['CK-B','chicken',20,7,'Prep kitchen'],['MN-A','mince',18,2,'Meat chiller'],['FS-A','fish',12,1,'Seafood ice bed'],['BR-A','bread',35,20,'Bakery shelf'],['RM-A','meals',22,4,'Grab-and-go fridge'],['RM-B','meals',14,16,'Prep bench']]){const p=PRODUCTS[product];batches.push({id,product,quantity,received:iso(now-24*36e5),limit:iso(now+(p.life-24)*36e5),location,hold:false,sensors:[-24,-18,-12,-6,0].map((h,i)=>({at:iso(now+h*36e5),temperature:i===0||i===4?p.ref:temp}))});}return {version:VERSION,asOf:iso(now),revision:0,batches,sales:Array.from({length:7},(_,i)=>({id:uid(),date:iso(now-(i+1)*864e5).slice(0,10),product:'strawberries',sector:'retail',kg:18+[2,6,1,5,0,4,3][i]})),inbound:[],decisions:[],outcomes:[],audit:[],settings:{sector:'retail',product:'strawberries',today:20,tomorrow:24,needIn:6,buffer:0,price:9,markdown:15,uplift:40,capacity:10,travel:2,destination:'Community kitchen',factor:CLIMATE.factor}};}
export function remaining(state,id){const b=state.batches.find(b=>b.id===id);return Math.max(0,b.quantity-state.outcomes.filter(o=>o.batchId===id).reduce((v,o)=>v+o.kg,0));}
export function quality(b,asOf,futureTemp){const now=Date.parse(asOf),start=Date.parse(b.received),p=PRODUCTS[b.product],readings=b.sensors.filter(x=>Date.parse(x.at)<=now).sort((a,b)=>Date.parse(a.at)-Date.parse(b.at));let reason='';if(b.hold)reason='Manual quality hold';else if(now<start)reason='Receipt is in the future';else if(now>=Date.parse(b.limit))reason='Date limit reached';else if(!readings.length||Date.parse(readings[0].at)>start)reason='History does not cover receipt';else if(hours(asOf,readings.at(-1).at)>6)reason='Last sensor reading is over 6 hours old';else if(readings.some((r,i)=>i>0&&hours(r.at,readings[i-1].at)>12))reason='Temperature history has a gap over 12 hours';let age=0;for(let i=0;i<readings.length;i++){const a=Math.max(start,Date.parse(readings[i].at)),z=i+1<readings.length?Date.parse(readings[i+1].at):now;age+=Math.max(0,(z-a)/36e5)*Math.pow(2,(readings[i].temperature-p.ref)/10);}const rate=Math.pow(2,((futureTemp??p.ref)-p.ref)/10),limitLeft=(Date.parse(b.limit)-now)/36e5,left=Math.max(0,Math.min((p.life-age)/rate,limitLeft));if(!reason&&left<=0)reason='Estimated quality window ended';return {hours:left,age,rate,capped:limitLeft<(p.life-age)/rate,blocked:!!reason,reason,method:`Illustrative Q10 = 2; future storage assumed at ${futureTemp??p.ref} °C`};}
export function curve(b,asOf,futureTemp){const p=PRODUCTS[b.product],now=Date.parse(asOf),start=Date.parse(b.received),readings=b.sensors.filter(x=>Date.parse(x.at)<=now).sort((a,b)=>Date.parse(a.at)-Date.parse(b.at)),points=[{t:start,pct:100}];let age=0;for(let i=0;i<readings.length;i++){const a=Math.max(start,Date.parse(readings[i].at)),z=i+1<readings.length?Date.parse(readings[i+1].at):now;if(z<=a)continue;age+=(z-a)/36e5*Math.pow(2,(readings[i].temperature-p.ref)/10);points.push({t:z,pct:Math.max(0,100*(1-age/p.life))});}const q=quality(b,asOf,futureTemp),life=Math.max(0,p.life-age)/q.rate;return {points,projection:[{t:now,pct:Math.max(0,100*(1-age/p.life))},{t:now+life*36e5,pct:0}],now,start,limit:Date.parse(b.limit),hours:q.hours};}
export function baseline(state,product,sector){const end=state.asOf.slice(0,10),start=iso(Date.parse(end)-7*864e5).slice(0,10);const rows=state.sales.filter(r=>r.product===product&&r.sector===sector&&r.date>=start&&r.date<end);const days=new Set(rows.map(r=>r.date));return {kg:days.size?rows.reduce((v,r)=>v+r.kg,0)/days.size:null,days:days.size,rows:rows.length};}
export function ingredientNeed(units,perUnit,yieldPercent){if(!finite(units)||!finite(perUnit,0,1000)||!finite(yieldPercent,1,100))throw Error('Enter non-negative units and ingredient quantity, and yield from 1 to 100%.');return units*perUnit/(yieldPercent/100);}
export function plan(state){const s=state.settings,list=state.batches.filter(b=>b.product===s.product).map(b=>({...b,left:remaining(state,b.id),q:quality(b,state.asOf)})).sort((a,b)=>a.q.hours-b.q.hours||a.id.localeCompare(b.id));let need=s.today;for(const b of list){b.used=!b.q.blocked&&b.q.hours>=s.needIn?Math.min(need,b.left):0;need-=b.used;b.after=b.left-b.used;}const carry=list.filter(b=>!b.q.blocked&&b.q.hours>=24+s.needIn).reduce((v,b)=>v+b.after,0);const inbound=state.inbound.filter(r=>r.product===s.product&&r.confirmed&&hours(r.arrival,state.asOf)>=0&&hours(r.arrival,state.asOf)<=24+s.needIn&&hours(r.limit,state.asOf)>=24+s.needIn).reduce((v,r)=>v+r.kg,0);const review=list.filter(b=>!b.q.blocked&&b.q.hours<24+s.needIn).reduce((v,b)=>v+b.after,0);const held=list.filter(b=>b.q.blocked).reduce((v,b)=>v+b.left,0);return {list,shortage:need,allocated:s.today-need,carry,inbound,review,held,order:Math.max(0,s.tomorrow+s.buffer-carry-inbound)};}
export function simulate(state,mode){const s=state.settings,rows=state.batches.filter(b=>b.product===s.product).map(b=>({id:b.id,received:b.received,left:remaining(state,b.id),q:quality(b,state.asOf)}));let sold=0,transferred=0;const initial=rows.reduce((v,b)=>v+b.left,0),held=rows.filter(b=>b.q.blocked).reduce((v,b)=>v+b.left,0);const usable=rows.filter(b=>!b.q.blocked);usable.sort(mode==='baseline'?(a,b)=>Date.parse(a.received)-Date.parse(b.received)||a.id.localeCompare(b.id):(a,b)=>a.q.hours-b.q.hours||a.id.localeCompare(b.id));for(let hour=1;hour<=24;hour++){let demand=s.today/24*(mode==='markdown'?1+s.uplift/100:1);for(const b of usable){if(b.q.hours<hour)continue;const n=Math.min(b.left,demand);b.left-=n;demand-=n;sold+=n;}}if(mode==='transfer'&&s.destination.trim()){let cap=s.capacity;for(const b of usable){if(b.q.hours<24+s.travel)continue;const n=Math.min(b.left,cap);b.left-=n;cap-=n;transferred+=n;}}const unresolved=usable.reduce((v,b)=>v+b.left,0),atRisk=usable.filter(b=>b.q.hours<24+s.needIn).reduce((v,b)=>v+b.left,0);return {mode,sold,transferred,unresolved,atRisk,held,initial,revenue:sold*s.price*(mode==='markdown'?1-s.markdown/100:1)};}
export function rescue(state){const s=state.settings,p=plan(state),out=[];for(const b of state.batches){const q=quality(b,state.asOf),row=b.product===s.product?p.list.find(x=>x.id===b.id):null,surplus=row?row.after:remaining(state,b.id);if(surplus<0.01)continue;const base={batchId:b.id,product:b.product,kg:Math.round(surplus*100)/100,hours:q.hours};if(q.blocked){const ended=/limit reached|window ended/.test(q.reason);out.push({...base,tier:ended?'recover':'check',action:ended?'discard':'inspect',why:q.reason+(ended?'. Route to compost or anaerobic digestion, not landfill.':'. Inspect before any release.')});continue;}if(q.hours>=24+s.needIn)continue;if(q.hours>=12)out.push({...base,tier:'prevent',action:'sell',why:`${Math.round(q.hours)} h left: use first or mark down ${s.markdown}% to clear before the quality window ends.`});else if(s.destination.trim()&&q.hours>=s.travel+4)out.push({...base,tier:'feed',action:'donate',destination:s.destination.trim(),why:`${Math.round(q.hours)} h left: enough for ${s.travel} h collection plus use by ${s.destination.trim()}.`});else out.push({...base,tier:'check',action:'inspect',why:`${Math.round(q.hours)} h left: too short to sell or donate safely. Inspect, then recover.`});}const rank=Object.fromEntries(HIERARCHY.map((h,i)=>[h[0],i]));return out.sort((a,b)=>a.hours-b.hours||rank[a.tier]-rank[b.tier]);}
export function impact(state){const f=state.settings.factor,base=simulate(state,'baseline'),modes=['rotate','markdown','transfer'].map(m=>simulate(state,m)),best=modes.reduce((a,b)=>b.atRisk<a.atRisk-1e-9?b:a),prevented=Math.max(0,base.atRisk-best.atRisk),total=k=>state.outcomes.filter(o=>k.includes(o.action)).reduce((v,o)=>v+o.kg,0),discarded=total(['discard']);return {factor:f,baseRisk:base.atRisk,best:best.mode,bestRisk:best.atRisk,prevented,avoided:prevented*f,recovered:total(['sell','use','donate']),donated:total(['donate']),discarded,discardEmissions:discarded*f};}
export function addAudit(state,action,detail){state.audit.unshift({id:uid(),at:new Date().toISOString(),action,detail});state.audit=state.audit.slice(0,1000);}
export function invalidate(state,reason){state.revision++;addAudit(state,'Data changed',reason);}
export function propose(state,{batchId,action,kg,destination='',reviewer='',note=''}){if(!['sell','use','donate','transfer','discard','inspect'].includes(action))throw Error('Choose a valid action.');const b=state.batches.find(b=>b.id===batchId);if(!b)throw Error('Select a batch.');if(!finite(kg,0.01)||kg>remaining(state,batchId)+1e-8)throw Error('Quantity must be positive and no greater than remaining stock.');if(quality(b,state.asOf).blocked&&!['inspect','discard'].includes(action))throw Error('This batch is held. Only inspection or discard can be proposed.');if(['transfer','donate'].includes(action)&&!destination.trim())throw Error('Enter the receiving destination.');const d={id:uid(),batchId,action,kg,destination:destination.trim(),reviewer:reviewer.trim(),note:note.trim(),status:'proposed',revision:state.revision,at:new Date().toISOString(),snapshot:{asOf:state.asOf,qualityHours:quality(b,state.asOf).hours,remaining:remaining(state,batchId)}};state.decisions.unshift(d);addAudit(state,'Decision proposed',`${b.id}: ${action}, ${kg} kg`);return d;}
export function approve(state,id,reviewer){const d=state.decisions.find(d=>d.id===id);if(!d||d.status!=='proposed')throw Error('Select a proposed decision.');if(d.revision!==state.revision)throw Error('Inputs changed. Create a new proposal from current data.');if(!reviewer.trim())throw Error('Enter the staff reviewer name.');d.status='approved';d.reviewer=reviewer.trim();d.approvedAt=new Date().toISOString();addAudit(state,'Decision approved',`${d.batchId}: ${d.action} by ${d.reviewer}`);}
export function recordOutcome(state,{decisionId,kg,evidence}){const d=state.decisions.find(d=>d.id===decisionId);if(!d||d.status!=='approved'||d.action==='inspect')throw Error('Select an approved stock movement.');if(d.revision!==state.revision)throw Error('This approval is stale. Create and approve a new proposal.');const consumed=state.outcomes.filter(o=>o.decisionId===d.id).reduce((v,o)=>v+o.kg,0);if(!finite(kg,0.01)||kg>d.kg-consumed+1e-8||kg>remaining(state,d.batchId)+1e-8)throw Error('Outcome exceeds the approval or remaining stock.');if(!evidence.trim())throw Error('Add an outcome reference or observation.');const o={id:uid(),decisionId:d.id,batchId:d.batchId,action:d.action,kg,evidence:evidence.trim(),at:new Date().toISOString()};state.outcomes.push(o);d.status='completed';invalidate(state,'Stock movement recorded');addAudit(state,'Outcome recorded',`${d.batchId}: ${kg} kg ${d.action}`);return o;}
export function validateState(raw){if(!raw||raw.version!==VERSION)throw Error('Unsupported backup version.');const text=(v,n=250)=>typeof v==='string'&&v.length<=n;const date=v=>text(v,40)&&Number.isFinite(Date.parse(v));const id=v=>text(v,100)&&v.length>0;const array=(v,n=10000)=>Array.isArray(v)&&v.length<=n;const fail=()=>{throw Error('Invalid or inconsistent backup. Nothing was imported.');};if(!date(raw.asOf)||!Number.isInteger(raw.revision)||raw.revision<0||!array(raw.batches,500)||!array(raw.sales)||!array(raw.inbound,500)||!array(raw.decisions)||!array(raw.outcomes)||!array(raw.audit,1000))fail();const st=structuredClone(raw),s=st.settings;if(s&&typeof s==='object'&&s.factor===undefined)s.factor=CLIMATE.factor;if(!s||!finite(s.factor,0,20)||!Object.hasOwn(SECTORS,s.sector)||!Object.hasOwn(PRODUCTS,s.product)||!text(s.destination)||!['today','tomorrow','buffer','price','capacity'].every(k=>finite(s[k]))||!finite(s.needIn,0,24)||!finite(s.markdown,0,100)||!finite(s.uplift,0,300)||!finite(s.travel,0,168))fail();const ids=new Set();for(const b of st.batches){if(!id(b.id)||ids.has(b.id)||!Object.hasOwn(PRODUCTS,b.product)||!finite(b.quantity,0.01)||!date(b.received)||!date(b.limit)||Date.parse(b.limit)<=Date.parse(b.received)||!text(b.location)||typeof b.hold!=='boolean'||!array(b.sensors,2000))fail();ids.add(b.id);const seen=new Set();for(const r of b.sensors){if(!date(r.at)||Date.parse(r.at)<Date.parse(b.received)||!finite(r.temperature,-40,80)||seen.has(r.at))fail();seen.add(r.at);}}
for(const r of st.sales)if(!id(r.id)||!/^\d{4}-\d{2}-\d{2}$/.test(r.date)||!date(r.date)||!Object.hasOwn(PRODUCTS,r.product)||!Object.hasOwn(SECTORS,r.sector)||!finite(r.kg))fail();for(const r of st.inbound)if(!id(r.id)||!Object.hasOwn(PRODUCTS,r.product)||!finite(r.kg,0.01)||!date(r.arrival)||!date(r.limit)||Date.parse(r.limit)<=Date.parse(r.arrival)||typeof r.confirmed!=='boolean')fail();const dids=new Set();for(const d of st.decisions){if(!id(d.id)||dids.has(d.id)||!ids.has(d.batchId)||!['sell','use','donate','transfer','discard','inspect'].includes(d.action)||!['proposed','approved','completed','cancelled'].includes(d.status)||!finite(d.kg,.01)||!text(d.destination)||!text(d.reviewer)||!text(d.note,2000)||!date(d.at)||!Number.isInteger(d.revision)||d.revision<0||d.revision>st.revision)fail();dids.add(d.id);}const oids=new Set();for(const o of st.outcomes){const d=st.decisions.find(d=>d.id===o.decisionId);if(!id(o.id)||oids.has(o.id)||!d||!ids.has(o.batchId)||o.batchId!==d.batchId||o.action!==d.action||o.action==='inspect'||d.status!=='completed'||!finite(o.kg,.01)||!text(o.evidence,2000)||!date(o.at))fail();oids.add(o.id);}for(const b of st.batches)if(st.outcomes.filter(o=>o.batchId===b.id).reduce((v,o)=>v+o.kg,0)>b.quantity+1e-8)fail();for(const d of st.decisions)if(st.outcomes.filter(o=>o.decisionId===d.id).reduce((v,o)=>v+o.kg,0)>d.kg+1e-8)fail();for(const a of st.audit)if(!id(a.id)||!date(a.at)||!text(a.action)||!text(a.detail,2000))fail();return st;}
export function csv(rows){return rows.map(row=>row.map(v=>{let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}).join(',')).join('\r\n');}
